# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-11-24 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20201123_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SearchInfo', models.CharField(max_length=255, verbose_name='检索信息')),
            ],
            options={
                'verbose_name': '检索记录表',
                'verbose_name_plural': '检索记录表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='searchrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.User', verbose_name='用户'),
        ),
    ]
